### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by ArcherN9** [hl3hl3/ARCoreMeasure#1]
Hey, thanks for making this open source. I'm trying to build an AR application as well, and learning from this is indispensable. It would have been a boon if commenting was added as well. Would you be able to take time out for it?

For example, I'm trying to make of this tiny method :
```
private boolean isMVPMatrixHitMotionEvent(float[] ModelViewProjectionMatrix, MotionEvent event){
            if(event == null){
                return false;
            }
            Matrix.multiplyMV(vertexResult, 0, ModelViewProjectionMatrix, 0, centerVertexOfCube, 0);
            // circle hit test
            float radius = (viewWidth / 2) * (cubeHitAreaRadius/vertexResult[3]);
            float dx = event.getX() - (viewWidth / 2) * (1 + vertexResult[0]/vertexResult[3]);
            float dy = event.getY() - (viewHeight / 2) * (1 - vertexResult[1]/vertexResult[3]);
            double distance = Math.sqrt(dx * dx + dy * dy);
//            // for debug
//            overlayViewForTest.setPoint("cubeCenter", screenX, screenY);
//            overlayViewForTest.postInvalidate();
            return distance < radius;
        }
```

I understand why is it being used. I don't understand the math calculations behind it - the how. Could you help please?

**Comment by hl3hl3** [comment]
Commenting
Commit: 573cb76a62fa1597026637e1ed4ad1273da8d196 [573cb76]
Parents: 2356e14467
Author: RebeccaHsieh <foutsau@gmail.com>
Date: 2017年11月21日 GMT+8 下午1:26:22
Labels: HEAD -> master
